/**
 * migrate.js — one-time migration from js/data.js → content/*.md markdown files.
 *
 * Run this once with:
 *   node scripts/migrate.js
 *
 * After migration, js/data.js is generated by scripts/build-data.js from the
 * markdown files on every Cloudflare Pages build. Editors never touch data.js.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CONTENT = path.join(ROOT, 'content');

// Load data.js by reading + evaluating it. (The file uses `const` exports,
// so we wrap it in a function to capture the values.)
const dataSrc = fs.readFileSync(path.join(ROOT, 'js', 'data.js'), 'utf8');
const capture = new Function(`${dataSrc}; return { CATS, KITTENS, LITTERS, TESTIMONIALS, BUSINESS, FORMS };`);
const { CATS, KITTENS, LITTERS, TESTIMONIALS, BUSINESS, FORMS } = capture();

// ---------- YAML frontmatter helpers ----------
// We hand-write YAML so we don't need a dependency. Only primitives + arrays.
function yamlValue(v) {
  if (v === null || v === undefined) return '""';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]';
    return '\n' + v.map(item => `  - ${yamlScalar(item)}`).join('\n');
  }
  return yamlScalar(v);
}
function yamlScalar(s) {
  const str = String(s);
  // Quote if contains special YAML characters, colons, or starts with a digit/symbol
  if (/[:#\[\]{}&*!|>'"%@`]|^\s|\s$|^\d|^-|^\s*$/.test(str) || str.includes('\n')) {
    return '"' + str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
  }
  return str;
}

function writeMarkdown(dir, filename, frontmatter, body = '') {
  const lines = ['---'];
  for (const [k, v] of Object.entries(frontmatter)) {
    lines.push(`${k}: ${yamlValue(v)}`);
  }
  lines.push('---');
  if (body) {
    lines.push('');
    lines.push(body);
  }
  lines.push('');  // Trailing newline
  const full = path.join(dir, filename);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(full, lines.join('\n'));
  console.log(`  → ${path.relative(ROOT, full)}`);
}

// ---------- Migrate cats ----------
console.log(`Migrating ${CATS.length} cats…`);
// Sort keeps queens-before-studs within each breed in the file system for tidiness
CATS.forEach((cat, idx) => {
  const order = idx;  // preserve original order so the site renders the same
  const frontmatter = {
    order,
    id: cat.id,
    name: cat.name,
    breed: cat.breed,
    role: cat.role,
    colour: cat.colour,
    registration: cat.registration || '',
    tagline: cat.tagline || '',
    siblings: cat.siblings || [],
    photos: (cat.photos || []).filter(p => p)  // strip empty slots
  };
  // personality becomes the markdown body so editors get a rich-text editor
  writeMarkdown(path.join(CONTENT, 'cats'), `${cat.id}.md`, frontmatter, cat.personality || '');
});

// ---------- Migrate kittens ----------
console.log(`Migrating ${KITTENS.length} kittens…`);
KITTENS.forEach((k, idx) => {
  const id = (k.name || `kitten-${idx}`).toLowerCase().replace(/[^a-z0-9]+/g, '-');
  writeMarkdown(path.join(CONTENT, 'kittens'), `${id}.md`, {
    order: idx,
    name: k.name,
    breed: k.breed,
    sex: k.sex,
    colour: k.colour,
    price: k.price || '',
    status: k.status || 'Available',
    photo: k.photo || ''
  });
});

// ---------- Migrate litters ----------
console.log(`Migrating ${LITTERS.length} litters…`);
LITTERS.forEach((l, idx) => {
  const id = `litter-${idx}`;
  writeMarkdown(path.join(CONTENT, 'litters'), `${id}.md`, {
    order: idx,
    breed: l.breed,
    expectedDate: l.expectedDate,
    expectedCount: l.expectedCount,
    notes: l.notes || ''
  });
});

// ---------- Migrate testimonials ----------
console.log(`Migrating ${TESTIMONIALS.length} testimonials…`);
TESTIMONIALS.forEach((t, idx) => {
  const id = `testimonial-${String(idx + 1).padStart(2, '0')}`;
  writeMarkdown(path.join(CONTENT, 'testimonials'), `${id}.md`, {
    order: idx,
    name: t.name,
    breed: t.breed,
    rating: t.rating
  }, t.comment);
});

// ---------- Migrate business + forms (settings) ----------
console.log('Migrating site settings…');
writeMarkdown(path.join(CONTENT, 'settings'), 'business.md', {
  name: BUSINESS.name,
  tagline: BUSINESS.tagline,
  url: BUSINESS.url,
  country: BUSINESS.country,
  instagram: BUSINESS.instagram,
  instagramHandle: BUSINESS.instagramHandle,
  tiktok: BUSINESS.tiktok,
  tiktokHandle: BUSINESS.tiktokHandle
});
writeMarkdown(path.join(CONTENT, 'settings'), 'forms.md', {
  kittenEnquiry: FORMS.kittenEnquiry,
  waitlist:      FORMS.waitlist,
  studBooking:   FORMS.studBooking,
  contact:       FORMS.contact
});

console.log('\n✓ Migration complete. Run `node scripts/build-data.js` to regenerate data.js.');
